name: bureau_du_leader_secretariat_general
description: "Gestionnaire d'Archives - DÃ©partement de la Communication CMCI"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  crypto: ^3.0.3
  open_file: ^3.3.2
  file_picker: ^6.1.1
  flutter_svg: ^2.0.9
  intl: ^0.18.0
  url_launcher: ^6.1.0
  pdf: ^3.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  msix: ^3.16.7

flutter:
  uses-material-design: true
  
  # Assets du projet
  assets:
    - assets/
    - assets/logo.jpg